services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: authkit_api_prod
    restart: always
    ports:
      - '8000:8000'
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    depends_on:
      migrator:
        condition: service_completed_successfully
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
    networks:
      - authkit_network

  migrator:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: authkit_migrator_prod
    restart: 'no'
    command: npx prisma migrate deploy
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - authkit_network

  redis:
    image: redis/redis-stack:latest
    container_name: authkit_redis_prod
    restart: always
    expose:
      - '6379'
    volumes:
      - redis_data_prod:/data
    networks:
      - authkit_network

  postgres:
    image: postgres:15-alpine
    container_name: authkit_postgres_prod
    restart: always
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - authkit_network

volumes:
  redis_data_prod:
  postgres_data_prod:

networks:
  authkit_network:
    driver: bridge
